config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  resources :products, only: [:index, :edit, :update, :delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	after_update :send_status_change_notification, if: :saved_change_to_active?
	after_save :schedule_product_launch_emails, if: :saved_change_to_launch_date?

	module Status
		ACTIVE = 'Active'.freeze
		IN_ACTIVE = 'Inactive'.freeze
	end

	def status
		active ? Status::ACTIVE : Status::IN_ACTIVE
	end

  private

  def send_status_change_notification
		User.normal_users.each do |user|
			ProductNotifierMailer.delay.status_change_notification(user, self)
    end
  end

  def schedule_product_launch_emails
    Product.where('launch_date > ?', DateTime.now).each do |product|
			User.normal_users.each do |user|
	      launch_time_in_user_timezone = product.launch_date.in_time_zone(user.timezone)
				ProductNotifierMailer.delay(run_at: launch_time_in_user_timezone).new_product_notification(user, product)
	    end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :normal_users, -> { where(admin: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :must_be_admin, only: :edit

  def index
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to products_path, notice: 'Product updated successfully.'
    else
      render :edit
    end
  end

   def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path, notice: 'Product deleted successfully.'
  end


  private

  def must_be_admin
    # validate admin
  	unless current_user && current_user.admin?
      redirect_to root_path, notice: "Normal user can't modify product details"
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :images, :launch_date, :price, :currency, :active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManagemetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class=”notice”><%= notice %></p>
    <p class=”alert”><%= alert %></p>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_for [@product] do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :images %>
    <%= f.text_area :images %>
  </div>

  <div>
    <%= f.label :launch_date %>
    <%= f.date_field :launch_date %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div>
    <%= f.label :currency %>
    <%= f.text_area :currency %>
  </div>

  <div>
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div>
    <%= f.submit 'Update Product' %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Product List</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Images</th>
      <th>Launch Date</th>
      <th>Price</th>
      <th>Currency</th>
      <th>Active</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.images %></td>
        <td><%= product.launch_date %></td>
        <td><%= product.price %></td>
        <td><%= product.currency %></td>
        <td><%= product.active ? 'Yes' : 'No' %></td>
         <td>
          <%= link_to 'Edit', edit_product_path(product) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>